# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanMu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u680f\u76ee\u540d\u79f0')),
                ('urlLM', models.CharField(max_length=255, verbose_name='\u680f\u76ee\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u680f\u76ee',
                'verbose_name_plural': '\u680f\u76ee',
            },
        ),
    ]
