# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:27
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ScrapyConfig', '0002_lanmu_nav_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='WenZhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u53d1\u5e03')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u4f5c\u8005',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.AlterField(
            model_name='lanmu',
            name='urlLM',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u680f\u76ee\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='wenzhang',
            name='lm',
            field=models.ManyToManyField(to='ScrapyConfig.LanMu', verbose_name='\u6240\u5c5e\u680f\u76ee'),
        ),
    ]
