# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 06:37
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapyConfig', '0003_auto_20160128_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wenzhang',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
